use_frameworks!

platform :ios, '8.0'

target 'MERPageViewController_Example' do
  pod 'MERPageViewController', :path => '../'

  target 'MERPageViewController_Tests' do
    inherit! :search_paths

    
  end
end
